FROM golang:1.10

# COPY . /go/src/github.com/just3ws/bohater-parkingu/api
WORKDIR /go/src/github.com/just3ws/bohater-parkingu/api

RUN go get github.com/golang/dep
RUN go get github.com/pilu/fresh

# RUN go get ./
# RUN go build

# CMD fresh

EXPOSE 8088
