---
openapi: 3.0.0
info:
  contact:
    email: mike@just3ws.com
  description: Parking rate for a given date and time range.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Bohater Parkingu API
  version: 1.0.1
servers:
  - description: Bohater Parkingu Rates API
    url: https://virtserver.swaggerhub.com/just3ws/bohater-parkingu/1.0.1
tags:
  - description: Operations available to regular developers
    name: developers
paths:
  /rate:
    get:
      description: >
        By passing in the start and end of your time range you can get the rate
        for the spot.
      operationId: lookupRate
      parameters:
        - description: Start of the desired rate period
          explode: true
          in: query
          name: starts
          required: true
          schema:
            format: date-time
            type: string
          style: form
        - description: End of the desired rate period.
          explode: true
          in: query
          name: ends
          required: true
          schema:
            format: date-time
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Rate'
                type: array
          description: Rate for the effective time range.
        204:
          content:
            text/plain:
              schema:
                example: unavilable
                title: unavailable
                type: string
          description: No available rates for date range
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Rate information not found
                type: string
          description: Not found response
      summary: Lookup rate info for date and time range.
      tags:
        - developers
components:
  schemas:
    Rate:
      example:
        price: 1900
        ends: 2000-01-23T04:56:07.000+00:00
        starts: 2000-01-23T04:56:07.000+00:00
      properties:
        price:
          example: 1900
          format: int32
          type: integer
        starts:
          format: date-time
          type: string
        ends:
          format: date-time
          type: string
      required:
        - ends
        - price
        - starts
      type: object
